export const ErrorCodes = Object.freeze({
    DEFAULT_ERROR: {
        code: "500",
        message: "An Error Occurred",
        polishMessage: "Wystąpił błąd",
        httpStatus: 500,
    },
    CUSTOM_INTERNAL_SERVER_ERROR: {
        code: "4000",
        message: "Internal Service Failure",
        polishMessage: "Błąd wewnętrznej usługi",
        httpStatus: 500,
    },
    FAILURE_OCCURED: {
        code: "5070",
        message: "Failure Occurred",
        polishMessage: "Wystąpiła awaria",
        httpStatus: 503,
    },
    RECORD_NOT_FOUND: {
        code: "5005",
        message: "Not Found",
        polishMessage: "Nie znaleziono zasobu",
        httpStatus: 404,
    },
    VALIDATION_FAILURE: {
        code: "5010",
        message: "Validation Failure. Invalid Arguments",
        polishMessage: "Błąd walidacji. Nieprawidłowe argumenty",
        httpStatus: 400,
    },
    PARAMETER_NOT_PROVIDED: {
        code: "5065",
        message: "Not Provided",
        polishMessage: "Niektóre z oczekiwanych danych wejściowych nie zostały dostarczone",
        httpStatus: 400,
    },
    INVALID_FORMAT: {
        code: "5015",
        message: "Invalid Format",
        polishMessage: "Niektóre oczekiwane dane wejściowe mają nieprawidłowy format",
        httpStatus: 400,
    },
    DUPLICATE_ENTRIES: {
        code: "5020",
        message: "Duplicating Entries",
        polishMessage: "Zduplikowane wpisy",
        httpStatus: 409,
    },
    BAD_REQUEST: {
        code: "5025",
        message: "Bad Request",
        polishMessage: "Nieprawidłowe żądanie",
        httpStatus: 400,
    },
    SENDING_EMAIL: {
        code: "5075",
        message: "Error Occurred During Sending Email",
        polishMessage: "Wystąpił błąd podczas wysyłania e-maila",
        httpStatus: 502,
    },
    PASSWORD_MISMATCH: {
        code: "5050",
        message: "Password Mismatch. Please Try again",
        polishMessage: "Hasło nie pasuje. Spróbuj ponownie",
        httpStatus: 400,
    },
    TOKEN_INVALID: {
        code: "5080",
        message: "Invalid Token",
        polishMessage: "Nieprawidłowy token",
        httpStatus: 400,
    },
    OTP_INVALID: {
        code: "5085",
        message: "OTP",
        polishMessage: "Nieprawidłowy kod OTP",
        httpStatus: 400,
    },
    ACTION_NOT_ALLOWED: {
        code: "5090",
        message: "Action Not Allowed",
        polishMessage: "Działanie niedozwolone",
        httpStatus: 400,
    },
    PERMISSION_DENIED: {
        code: "5055",
        message: "Permission Denied",
        polishMessage: "Odmowa dostępu",
        httpStatus: 403,
    },
    UNAUTHORIZED: {
        code: "5060",
        message: "Authentication Required",
        polishMessage: "Wymagana autoryzacja",
        httpStatus: 401,
    },
    SUSPENDED: {
        code: "6010",
        message: "Suspended Service Provider",
        polishMessage: "Dostawca usług zawieszony",
        httpStatus: 403,
    },
    DELETION_ABANDONED: {
        code: "6015",
        message: "Deletion Abandoned",
        polishMessage: "Usunięcie przerwane",
        httpStatus: 400,
    },
    INVALID_ROLE: {
        code: "5095",
        message: "Invalid Role or Insufficient Permissions",
        polishMessage: "Nieprawidłowa rola lub niewystarczające uprawnienia",
        httpStatus: 403,
    },
    INVALID_STATUS: {
        code: "5100",
        message: "Not in a Valid Status",
        polishMessage: "Nie w prawidłowym statusie",
        httpStatus: 400,
    },
});